version: "3"

services:

  billing_service:
    extends:
      file: docker-compose-billing.yaml
      service: billing_service
    volumes:
      - ./src:/opt/admin
    environment:
      DJANGO_ADMIN_BILLING_DEBUG: "True"
    ports:
      - 8000:8000

  celery:
    extends:
      file: docker-compose-billing.yaml
      service: celery
    profiles:
      - celery

  flower:
    extends:
      file: docker-compose-billing.yaml
      service: flower
    profiles:
      - celery

  auth_service:
    extends:
      file: docker-compose-auth.yaml
      service: auth_service
    volumes:
      - ./auth_service/src:/home/app
    environment:
      AUTH_DEBUG: "True"
      AUTH_PROJECT_ROOT_URL: 
    ports:
      - 8001:8000
    profiles:
      - auth

  postgres:
    extends:
      file: docker-compose-common.yaml
      service: postgres
    environment:
      POSTGRES_USER: ${PG_ADMIN_BILLING_USER}
      POSTGRES_DB: ${PG_ADMIN_BILLING_PASSWORD}
      POSTGRES_PASSWORD: ${PG_ADMIN_BILLING_DB_NAME}
    ports:
      - 5432:5432

  redis:
    extends:
      file: docker-compose-common.yaml
      service: redis
    ports:
      - 6379:6379
    profiles:
      - celery
      - auth

  rabbit:
    extends:
      file: docker-compose-common.yaml
      service: rabbit
    profiles:
      - celery

volumes:
  db_volume:
  static_volume:
  media_volume:
  worker_data:
  flower_data:

secrets:
  rsa_pub:
    file: ./keys/rsa.pub
  rsa_priv:
    file: ./keys/rsa.private
  service_accounts:
    file: ./keys/services.json
