version: "3"

services:

  logstash:
    image: logstash:8.10.2
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
      ES_HOST: "elasticsearch:9200"
    command: logstash -f /config/logstash.conf
    ports:
      - "5000:5000/udp"
    configs:
      - source: logstash_config
        target: /config/logstash.conf

  elasticsearch:
    image: elasticsearch:8.10.2
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
      ES_JAVA_OPTS: "-Xms200m -Xmx200m"
    healthcheck:
      test: "curl -f 127.0.0.1:9200 || exit 1"
      interval: 10s
      timeout: 30s
    expose:
      - 9200

  kibana:
    image: kibana:8.10.2
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - 5601:5601

  jaeger:
    image: jaegertracing/all-in-one:latest
    depends_on:
      - elasticsearch
    restart: on-failure
    environment:
      SPAN_STORAGE_TYPE: elasticsearch
      ES_SERVER_URLS: "http://elasticsearch:9200"
    ports:
      - 6831:6831/udp
      - 16686:16686
