version: "3"

services:

  billing-service:
    extends:
      file: docker-compose-billing.yaml
      service: billing-service
    volumes:
      - ./src:/opt/admin
    environment:
      DJANGO_ADMIN_BILLING_DEBUG: "True"
    ports:
      - 8000:8000

  celery:
    extends:
      file: docker-compose-billing.yaml
      service: celery
    environment:
      DJANGO_ADMIN_BILLING_DEBUG: "True"
    profiles:
      - celery

  flower:
    extends:
      file: docker-compose-billing.yaml
      service: flower
    profiles:
      - celery

  auth_service:
    extends:
      file: docker-compose-auth.yaml
      service: auth_service
    volumes:
      - ./auth_service/src:/home/app
    environment:
      AUTH_DEBUG: "True"
      AUTH_PROJECT_ROOT_URL:
    ports:
      - 8001:8000
    profiles:
      - auth
      - notification

  notification-api:
    extends:
      file: docker-compose-notification.yaml
      service: notification-api
    volumes:
      - "./notification_service/notification_api/src:/opt/app/"
    environment:
      NOTIFY_DEBUG: "True"
      NOTIFY_LOGGING_LEVEL: "DEBUG"
      NOTIFY_PROJECT_ROOT_URL:
    ports:
      - 8002:8001
    profiles:
      - notification

  notification_admin:
    extends:
      file: docker-compose-notification.yaml
      service: notification_admin
    volumes:
      - "./notification_service/admin:/opt/admin/"
    environment:
      DJANGO_ADMIN_NF_DEBUG: "True"
    ports:
      - 8003:8000
    profiles:
      - notification

  regular_notify_converter:
    extends:
      file: docker-compose-notification.yaml
      service: regular_notify_converter
    profiles:
      - notification

  notification-notify-sender:
    extends:
      file: docker-compose-notification.yaml
      service: notification-notify-sender
    profiles:
      - notification

  notification-user-provider:
    extends:
      file: docker-compose-notification.yaml
      service: notification-user-provider
    profiles:
      - notification

  notification-rabbit-setup:
    extends:
      file: docker-compose-notification.yaml
      service: notification-rabbit-setup
    profiles:
      - notification

  mailpit:
    extends:
      file: docker-compose-notification.yaml
      service: mailpit
    profiles:
      - notification

  postgres:
    extends:
      file: docker-compose-common.yaml
      service: postgres
    environment:
      POSTGRES_USER: ${PG_ADMIN_BILLING_USER}
      POSTGRES_DB: ${PG_ADMIN_BILLING_PASSWORD}
      POSTGRES_PASSWORD: ${PG_ADMIN_BILLING_DB_NAME}
    ports:
      - 5432:5432

  redis:
    extends:
      file: docker-compose-common.yaml
      service: redis
    ports:
      - 6379:6379
    profiles:
      - notification

  rabbit:
    extends:
      file: docker-compose-common.yaml
      service: rabbit
    profiles:
      - celery
      - notification

volumes:
  db_volume:
  static_volume:
  media_volume:
  worker_data:
  flower_data:


secrets:
  rsa_pub:
    file: ./keys/rsa.pub
  rsa_priv:
    file: ./keys/rsa.private
  service_accounts:
    file: ./keys/services.json

configs:
  billing_config:
    file: ./configs/billing-dev.yaml
