# Generated by Django 5.0 on 2024-01-16 02:52

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=30)),
                ("description", models.TextField()),
                ("amount", models.FloatField()),
                ("period", models.TextField(choices=[("month", "Month"), ("year", "Year")])),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserSubscription",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        verbose_name="created_at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_default=django.db.models.functions.datetime.Now(), verbose_name="updated_at"
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("expire_at", models.DateTimeField()),
                ("prolong", models.BooleanField()),
                (
                    "subscription",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="subscriptions.subscription"),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="users.user")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
