# Generated by Django 5.0 on 2024-01-31 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubscription",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="usersubscription",
            name="user_id",
            field=models.UUIDField(),
        ),
    ]
