# Generated by Django 5.0 on 2024-01-16 17:14

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payments",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        verbose_name="created_at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_default=django.db.models.functions.datetime.Now(), verbose_name="updated_at"
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("user_id", models.UUIDField(verbose_name="user_id")),
                ("user_purchase_item_id", models.UUIDField(verbose_name="user_purchase_item_id")),
                ("external_payment_id", models.CharField(verbose_name="external_payment_id")),
                ("payment_method", models.CharField(blank=True, verbose_name="payment_method")),
                ("payment_method_id", models.CharField(blank=True, verbose_name="payment_method_id")),
                ("amount", models.FloatField(verbose_name="amount")),
                (
                    "currency",
                    models.CharField(choices=[("RUB", "Rub"), ("USD", "Usd"), ("EUR", "Eur")], verbose_name="currency"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("succeeded", "Succeeded"), ("canceled", "Canceled"), ("pending", "Pending")],
                        default="pending",
                        verbose_name="status",
                    ),
                ),
                ("recurrent", models.BooleanField(verbose_name="recurrent")),
                ("refundable", models.BooleanField(verbose_name="refundable")),
            ],
            options={
                "verbose_name": "payments",
                "verbose_name_plural": "payments",
                "db_table": 'public"."payments',
                "indexes": [
                    models.Index(fields=["user_id", "user_purchase_item_id"], name="user_id_item_id_idx"),
                    models.Index(fields=["external_payment_id"], name="external_payment_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Refunds",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        verbose_name="created_at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_default=django.db.models.functions.datetime.Now(), verbose_name="updated_at"
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("user_id", models.UUIDField(verbose_name="user_id")),
                ("external_refund_id", models.CharField(verbose_name="external_refund_id")),
                ("amount", models.FloatField(verbose_name="amount")),
                (
                    "currency",
                    models.CharField(choices=[("RUB", "Rub"), ("USD", "Usd"), ("EUR", "Eur")], verbose_name="currency"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("succeeded", "Succeeded"), ("canceled", "Canceled"), ("pending", "Pending")],
                        default="pending",
                        verbose_name="status",
                    ),
                ),
                ("reason", models.TextField(verbose_name="reason")),
                ("payment", models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to="billing.payments")),
            ],
            options={
                "verbose_name": "refunds",
                "verbose_name_plural": "refunds",
                "db_table": 'public"."refunds',
                "indexes": [
                    models.Index(fields=["user_id", "payment"], name="user_id_payment_id_idx"),
                    models.Index(fields=["external_refund_id"], name="external_refund_idx"),
                ],
            },
        ),
    ]
