# Generated by Django 5.0 on 2024-02-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0002_alter_payments_external_payment_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="refunds",
            name="user_subscription_id",
            field=models.UUIDField(blank=True, unique=True, verbose_name="user_subscription_id"),
        ),
    ]
