import os

REDIS_HOST = os.environ["DJANGO_ADMIN_NF_REDIS_HOST"]
REDIS_PORT = os.environ["DJANGO_ADMIN_NF_REDIS_PORT"]

CELERY_BROKER_URL = f"redis://{REDIS_HOST}:{REDIS_PORT}/0"
CELERY_BROKER_TRANSPORT_OPTIONS = {"visibility_timeout": 3600}
CELERY_RESULT_BACKEND = f"redis://{REDIS_HOST}:{REDIS_PORT}/0"
CELERY_ACCEPT_CONTENT = ["application/json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_IMPORTS = ("notifications.tasks",)
