@startuml
autonumber
actor customer as "Customer"
participant subscription_app as "Subscription app"
participant billing_app as "Billing app"
database db as "DB"
participant celery as "Celery"
participant bank_service as "Bank service"
participant notification_service as "Notification service" #LightBlue

customer -> subscription_app ++: subscription, user_id
subscription_app -> db ++: GET: user, subscription
db -> subscription_app --: subscription, user
subscription_app -> customer --: subscription list

customer -> billing_app ++: user_id, subscription_id
billing_app -> db ++: GET: subscriptions
db -> billing_app --: subscriptions
billing_app -> db ++: CREATE: payment, status=PENDING
db -> billing_app --: payment_id
billing_app -> bank_service ++: payment
bank_service -> billing_app --: payment link
billing_app -> customer --: payment link

customer -> customer: make payment

bank_service -> billing_app: WEBHOOK: payment
billing_app -> bank_service ++: payment_id
bank_service -> billing_app --: status
billing_app -> celery: payment: status, user, subscription
celery -> notification_service: user, payment, subscription
celery -> db: UPDATE: payment, status

@enduml