name: python-tests

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/**'
      - 'src/**'
  push:
    branches: [ "main" ]
    paths:
      - '.github/**'
      - 'src/**'

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Create directories
        run: |
          mkdir -p reports/api/mypy/

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy lxml

      - name: Lint with ruff
        uses: chartboost/ruff-action@v1
        with:
          src: "./src"
          version: 0.0.259

      - name: Lint with mypy
        run: |
          mypy --html-report reports/api/mypy/ src/* || true

      - name: Upload reports
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: reports/
